version: 1
disable_existing_loggers: False
formatters:
    simple:
        format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: simple
        stream: ext://sys.stdout

    project_1_handler:
        class: logging.handlers.RotatingFileHandler
        level: INFO
        formatter: simple
        filename: logs/project_1.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8
        mode: w

    project_2_handler:
        class: logging.handlers.RotatingFileHandler
        level: INFO
        formatter: simple
        filename: logs/project_2.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

    logger_handler:
        class: logging.handlers.RotatingFileHandler
        level: INFO
        formatter: simple
        filename: logs/logger_handler.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

    info_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: INFO
        formatter: simple
        filename: logs/project_2.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

    sample:
        class: logging.handlers.RotatingFileHandler
        level: INFO
        formatter: simple
        filename: logs/sample.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

    error_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: ERROR
        formatter: simple
        filename: errors.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

loggers:
    sample:
        level: INFO
        handlers: [console, sample]
        propagate: no

    project_1:
        level: INFO
        handlers: [console, project_1_handler]
        propagate: no

    project_2:
        level: INFO
        handlers: [console, project_2_handler]
        propagate: no

    logger:
        level: INFO
        handlers: [console, logger_handler]
        propagate: no

root:
    level: INFO
    handlers: [console, info_file_handler, error_file_handler]